spring:
  redis:
    hostName: localhost
    port: 6379
    database: 2
    password:
  kafka:
    consumer:
      group-id: kafka
    bootstrap-servers: localhost:9092


# 日志配置
logging:
  level:
    org.springframework.web: debug
