spring:
  application:
    name: data-service
  session:
    store-type: none
  datasource:
    platform: postgres  
    url: jdbc:postgresql://139.159.215.157:5432/postgres?useSSL=false
    username: postgres
    password: _Admin001
#
#    url: jdbc:postgresql://192.168.1.100:5432/postgres?useSSL=false
#        username: postgres
#        password: root
    driver-class-name: org.postgresql.Driver
    # 配置数据源
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
      auto-commit: true
      idle-timeout: 10000
      pool-name: HikariDS
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
      maximum-pool-size: 15
  redis:
    hostName: 127.0.0.1
    port: 6379
    database: 2
    password:
  kafka:
    consumer:
      group-id: kafka
      heartbeat-interval: 300000
    bootstrap-servers: localhost:9092
  jackson:
    time-zone: Asia/Shanghai
#    bootstrap-servers: 10.13.131.176:9094

#mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
logging:
  level:
    com:
      yihexinda:
          dataservice:
             dao: debug

  
  