spring:
  profiles:
    active: dev
  redis:
    hostName: localhost
    port: 6379
    database: 2
    password:
  kafka:
    consumer:
      group-id: kafka
    bootstrap-servers: localhost:9092
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 60000
        loggerLevel: basic

# 日志配置
logging:
  level:
    org.springframework.web: debug
