spring:
  profiles:
    active: prod
  application:
    name: pc-web
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    suffix: .ftl
  jackson:
    time-zone: Asia/Shanghai
server:
  port: 8100
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 60000
        loggerLevel: basic
