spring:
  application:
    name: node-web
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    suffix: .ftl
  redis:
    host: localhost
    port: 6379
    database: 2
#    password: shenzhenair
  kafka:
    consumer:
      group-id: kafka
    bootstrap-servers: localhost:9092
  jackson:
    time-zone: Asia/Shanghai
#    bootstrap-servers: 10.13.131.176:9094
server:
  port: 8084
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 60000
        loggerLevel: basic
node-web:
  base-path: /node-web
  check-login-and-redir-url: /asms/login/asms/checkLogin
  session-name: scheduling-session
  asms-host: http://10.12.69.67:8080
  get-login-username-url: /asms/login/asms/token2bh

---
spring:
  profiles: docker
  application:
    name: node-web
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    suffix: .ftl
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 2
  kafka:
    consumer:
      group-id: kafka-docker
    bootstrap-servers: ${KAFKA_SERVERS}
  jackson:
    time-zone: Asia/Shanghai
server:
  port: 8084
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 60000
        loggerLevel: basic
node-web:
  base-path: /node-web
  check-login-and-redir-url: /asms/login/asms/checkLogin
  session-name: scheduling-session
  asms-host: ${ASMS_HOST}
  get-login-username-url: /asms/login/asms/token2bh